# Generated by Django 4.1.6 on 2023-02-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karta.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='image',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karta.point'),
        ),
    ]
