# Generated by Django 4.1.6 on 2023-02-25 15:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('karta', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Інформація'),
        ),
    ]
