# Generated by Django 4.1.6 on 2023-02-26 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import karta.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karta', '0003_alter_point_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='photo',
            field=models.ImageField(default='default/no_image.jpeg', upload_to=karta.models.Point.image_upload_to),
        ),
        migrations.AlterField(
            model_name='point',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
