# Generated by Django 4.1.6 on 2023-03-19 09:33

from django.db import migrations, models
import karta.models


class Migration(migrations.Migration):

    dependencies = [
        ('karta', '0004_point_photo_alter_point_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=karta.models.point_directory_path),
        ),
        migrations.AlterField(
            model_name='point',
            name='slug',
            field=models.SlugField(default=karta.models.Point.default_slug, max_length=100),
        ),
    ]
